[package]
name = "realworld"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = "1.0.216"
sqlx = { version = "0.8.2", features = ["runtime-tokio-rustls", "sqlite", "migrate"] }
tokio = { version = "1.42.0", features = ["full"] }
